[tox]
envlist = py312
minversion = 2.0
skipsdist = false
skip_missing_interpreters = true

[testenv:docs]
deps =
  mkdocs-material==9.1.0
  mkdocs-glightbox
commands = mkdocs serve --dev-addr 0.0.0.0:8181 --livereload

[testenv:docs-deploy]
deps =
  mkdocs-material==9.1.0
  mkdocs-glightbox
commands = mkdocs gh-deploy --force
