name: build

on:
  push:
    branches-ignore:
      - master
    tags:
      - '*'

jobs:
  Build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: exordos/exordos_ci/.github/workflows/element_build.yml@master
    with:
      push-target: exordos_repo
    secrets:
      PUSH_CFG: ${{ secrets.PUSH_EXORDOS_CFG }}
  Test:
    needs: Build
    uses: exordos/exordos_ci/.github/workflows/element_realm_test.yml@master
    with:
      elements: empty
      version: ${{ needs.Build.outputs.version }}
    secrets: inherit
