name: Build GitHub Pages
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - mkdocs.yml
  workflow_dispatch:

jobs:
  Docs:
    uses: exordos/exordos_ci/.github/workflows/docs.yml@master
    permissions:
      contents: write
      pages: write
      id-token: write
